services:

  Szczyglis\ExtendedDumpBundle\Core\Dumper:
    autowire: true

  Szczyglis\ExtendedDumpBundle\Core\Generator:
    autowire: true
    arguments:
      0: []

  Szczyglis\ExtendedDumpBundle\Core\Output:
    autowire: true

  Szczyglis\ExtendedDumpBundle\Core\InternalDumper:
    autowire: true

  Szczyglis\ExtendedDumpBundle\Internals\RequestDumper:
    autowire: true

  Szczyglis\ExtendedDumpBundle\Internals\ServerDumper:
    autowire: true

  Szczyglis\ExtendedDumpBundle\Internals\UserDumper:
    autowire: true

  Szczyglis\ExtendedDumpBundle\Internals\DoctrineDumper:
    autowire: true

  Szczyglis\ExtendedDumpBundle\Internals\ParametersDumper:
    autowire: true

  Szczyglis\ExtendedDumpBundle\EventSubscriber\ResponseSubscriber:
    autowire: true
    tags:
      - { name: kernel.event_subscriber }

  Szczyglis\ExtendedDumpBundle\Twig\ExtendedDumpTwigExtension:
    tags:
      - { name: twig.extension }
